#:kivy 2.1.0
#:include kv/homescreen.kv
#:include kv/settingsscreen.kv
#:include kv/startscreen.kv

GridLayout:
    cols: 1
    ScreenManager:
        id: screen_manager
        StartScreen:
            name: "start_screen"
            id: start_screen
        HomeScreen:
            name: "home_screen"
            id: home_screen
        SettingsScreen:
            name: "settings_screen"
            id: settings_screen